"""Add devices table

Revision ID: 625904389f54
Revises: ddcfba3c7d5c
Create Date: 2023-06-13 18:22:14.658784

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "625904389f54"
down_revision = "ddcfba3c7d5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_general_ci",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("devices")
    # ### end Alembic commands ###
